environment:
    apitoken: ENC[AES256_GCM,data:oIN9tzXEA6CVX8Gx22GY1PboOI2HvyCIv+dnzyaK3Us=,iv:pjGDeliHqUfllC3O82MPDk1Y3xbgkgryhbcky5zqc8U=,tag:zvRsbBc0e9YRUXc5ns389A==,type:str]
    zoneid: ENC[AES256_GCM,data:JcZj+jKLIJIE0x8FDAToLHc85biURA==,iv:0evnLL31xqmld9/3zU/AJF7LIr7loPD72P9Q10Hkj+Y=,tag:ozyeyb4MFYP7y2/3ojMbCg==,type:str]
    recordid: ENC[AES256_GCM,data:hGv48P6oH7oGeR3Mv9b9n/9A8Nszr5vDfvDPbUPWaCE=,iv:VwDSmv/Vv2RmowTYFMmWTizLMd3YUDJ902NzSgimnOI=,tag:yk0cqsJup8A7zeRp0D29dA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d085lpynkxxf0mfus0rd3qq0r38clwz9d5ddrl79x982z00j6qsqq8f54g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2Wno3cFgrYWlRdWNybVd5
            bEMyRlhmMnU5Y3NoclNxV3hIdkJrdzUxY1Q0CkpzYnFQRXhqSFIwSUVETmlQYzdw
            VXpoZkcyelZycFo1dXZOcVNybUF1cUkKLS0tIFZzczFhQVFaRkFVcmVEWlpBaXli
            OVplVHJTNFZjMm1mM1V4Tmh2U21KcG8K7P3BYbYhgqw+kMepyKS0bY9/qAAuJXiB
            qW2UOdYfkxU2JrmQ7xk1K+FT88OjYXx2m9vG29fYCj3iawpzU09pUQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tg4tv8h3yh7qhzuhsm9v0j2mkk3adukv5765vyq5ymfpkqp7nsysvktfu8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNT29tQmEzeVNLdldjMlox
            QzlnT0g1SXdqUXJ5NWh3Ry8vaFcrK3FGaWxVCnNhQmkvTkNlamxHaUpkcDZIRFJB
            d1IxbnBDd0Z1NElZaUI4TjRqeWpOZHMKLS0tIDNxYk04RzFKOVFNRE9JRS9zdlhN
            RCsycU4yaE9KUTlNM1BONkthQzdIbG8KdKyUsDTv+/NoQY4N+eVV7dcinQPQBm2p
            6MZK7T3cQWoYxcFAn9RFo2Stq02mxcRL3e6wWevqJCRWrX74BEcR/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-14T19:26:09Z"
    mac: ENC[AES256_GCM,data:hdQDFpyyHJANMVEsxOCdz6r16fyYeyyblYV1McZwfh+uXmUVikRUrxVrHrVcHYnMut3P4S0FZWdqsreAt9/boROCcGmMLTLbsfWTDmRNvX2YYJMJDhu4sK/pS/nZdiAnM49mh9B09YDrM1sUnA0VwAvjrCY6SpPcYKdpbNNRZ0M=,iv:6JR0Rk90kSB7/sWCX2LFYxBijYtoB2DYo8lrcnqDTcE=,tag:xV5RXXk5qiMAuInqiiI2Kw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
